# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DNS_Tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from userInputSim import Ui_userInputSim # from userInputSim.py import Class Ui_userInputSim
from userInputCom import Ui_userInputCom  # from userInputSim.py import Class Ui_userInputCom


class Ui_MainWindow(object):
    def openWindowSim(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_userInputSim()
        self.ui.setupUi(self.window)
        # MainWindow.hide()
        self.window.show()

    def openWindowCom(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_userInputCom()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("CI2 DNS Search Tools")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(20, 50, 191, 192))
        self.treeView.setObjectName("treeView")
        self.simpleDnsSearch_btn = QtWidgets.QPushButton(self.centralwidget)
        self.simpleDnsSearch_btn.setGeometry(QtCore.QRect(50, 90, 121, 23))
        self.simpleDnsSearch_btn.setObjectName("simpleDnsSearch_btn")

        self.simpleDnsSearch_btn.clicked.connect(self.openWindowSim)

        self.comDnsSearch_btn = QtWidgets.QPushButton(self.centralwidget)
        self.comDnsSearch_btn.setGeometry(QtCore.QRect(50, 150, 141, 31))
        self.comDnsSearch_btn.setObjectName("comDnsSearch_btn")

        self.comDnsSearch_btn.clicked.connect(self.openWindowCom)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CI2 DNS Search tools"))
        self.pushButton.setText(_translate("MainWindow", "DNS Search Tool"))
        self.simpleDnsSearch_btn.setText(_translate("MainWindow", "Simple DNS Search"))
        self.comDnsSearch_btn.setText(_translate("MainWindow", "Comprehensive DNS Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
