# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userInputCom.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userInputCom(object):
    def setupUi(self, userInputCom):
        userInputCom.setObjectName("User Input Comprehensive DNS Search")
        userInputCom.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(userInputCom)
        self.centralwidget.setObjectName("centralwidget")
        self.userInput = QtWidgets.QLineEdit(self.centralwidget)
        self.userInput.setGeometry(QtCore.QRect(280, 100, 221, 41))
        self.userInput.setObjectName("userInput")
        self.webAddress_label = QtWidgets.QLabel(self.centralwidget)
        self.webAddress_label.setGeometry(QtCore.QRect(100, 100, 111, 31))
        self.webAddress_label.setObjectName("webAddress_label")
        self.Com_search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Com_search_btn.setGeometry(QtCore.QRect(360, 190, 75, 23))
        self.Com_search_btn.setObjectName("com_search_btn")
        self.IP_label = QtWidgets.QLabel(self.centralwidget)
        self.IP_label.setGeometry(QtCore.QRect(100, 260, 101, 20))
        self.IP_label.setObjectName("IP_label")
        self.ipResult = QtWidgets.QLineEdit(self.centralwidget)
        self.ipResult.setGeometry(QtCore.QRect(290, 250, 221, 41))
        self.ipResult.setObjectName("ipResult")
        self.saveIP_btn = QtWidgets.QPushButton(self.centralwidget)
        self.saveIP_btn.setGeometry(QtCore.QRect(360, 370, 91, 23))
        self.saveIP_btn.setObjectName("saveIP_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 281, 41))
        self.label.setObjectName("label")
        userInputCom.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(userInputCom)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        userInputCom.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(userInputCom)
        self.statusbar.setObjectName("statusbar")
        userInputCom.setStatusBar(self.statusbar)

        self.retranslateUi(userInputCom)
        QtCore.QMetaObject.connectSlotsByName(userInputCom)

    def retranslateUi(self, userInputCom):
        _translate = QtCore.QCoreApplication.translate
        userInputCom.setWindowTitle(_translate("MainWindow", "Comprehensive DNS Search User Input"))
        self.webAddress_label.setText(_translate("MainWindow", "Website Address"))
        self.Com_search_btn.setText(_translate("MainWindow", "Search"))
        self.IP_label.setText(_translate("MainWindow", "IP Address Result"))
        self.saveIP_btn.setText(_translate("MainWindow", "Save "))
        self.label.setText(_translate("MainWindow", "Comprehensive DNS search User Input"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userInputCom = QtWidgets.QMainWindow()
    ui = Ui_userInputCom()
    ui.setupUi(userInputCom)
    userInputCom.show()
    sys.exit(app.exec_())
